apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "ecr-cleaner.fullname" . }}
  labels:
    {{- include "ecr-cleaner.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    metadata:
      labels:
        {{- include "ecr-cleaner.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ecr-cleaner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          {{- if .Values.config.days }}
          - "--days"
          - "{{ .Values.config.days}}"
          {{- end }}
          {{- if .Values.config.debug }}
          - "--debug"
          {{- end }}
          {{- if .Values.config.dryRun }}
          - "--dry-run"
          {{- end }}
          {{- if .Values.config.force }}
          - "--force"
          {{- end }}
          {{- if .Values.config.noSemver }}
          - "--no-semver"
          {{- end }}
          {{- if .Values.config.region }}
          - "--region"
          - "{{ .Values.config.region}}"
          {{- end }}
          {{- if .Values.config.repo }}
          - "--repo"
          - "{{ .Values.config.repo}}"
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
