name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - uses: actions/checkout@v2

    - run: go get -v -t -d ./...
    - run: go test -v ./...

